import type { Icon } from '@tabler/icons-react';
import {
  IconHeart,
  IconHeartFilled,
  IconThumbUp,
  IconThumbUpFilled,
  IconStar,
  IconStarFilled,
  IconSparkles,
  IconFlame,
  IconFlameFilled,
  IconAward,
  IconAwardFilled,
  IconTrophy,
  IconTrophyFilled,
  IconCrown,
  IconBolt,
  IconBoltFilled,
  IconRocket,
  IconRosetteDiscountCheck,
  IconRosetteDiscountCheckFilled,
  IconArrowRight,
  IconArrowLeft,
  IconArrowUp,
  IconArrowDown,
  IconArrowUpRight,
  IconArrowBigRight,
  IconArrowBigRightFilled,
  IconArrowNarrowRight,
  IconChevronRight,
  IconChevronLeft,
  IconChevronUp,
  IconChevronDown,
  IconCircleArrowRight,
  IconCircleArrowRightFilled,
  IconArrowsRightLeft,
  IconRefresh,
  IconShoppingCart,
  IconShoppingBag,
  IconShoppingBagCheck,
  IconCreditCard,
  IconWallet,
  IconCash,
  IconCoin,
  IconCoinFilled,
  IconCurrencyDollar,
  IconCurrencyEuro,
  IconReceipt,
  IconReceiptOff,
  IconGift,
  IconGiftFilled,
  IconDiscount,
  IconDiscountFilled,
  IconTag,
  IconTagFilled,
  IconTagsFilled,
  IconBriefcase,
  IconBriefcaseFilled,
  IconBuildingStore,
  IconChartBar,
  IconChartLine,
  IconChartPie,
  IconChartPieFilled,
  IconTrendingUp,
  IconTrendingDown,
  IconTarget,
  IconTargetArrow,
  IconBrandFacebook,
  IconBrandInstagram,
  IconBrandLinkedin,
  IconBrandTiktok,
  IconBrandX,
  IconBrandYoutube,
  IconBrandWhatsapp,
  IconBrandTelegram,
  IconBrandPinterest,
  IconBrandSnapchat,
  IconShare,
  IconShare2,
  IconShare3,
  IconMessageCircle,
  IconMessageCircleFilled,
  IconMessage,
  IconMessageFilled,
  IconMail,
  IconMailFilled,
  IconPhone,
  IconPhoneFilled,
  IconBell,
  IconBellFilled,
  IconBellRingingFilled,
  IconAt,
  IconHash,
  IconCalendar,
  IconCalendarFilled,
  IconCalendarEvent,
  IconCalendarTime,
  IconClock,
  IconClockFilled,
  IconClockHour9,
  IconHourglass,
  IconAlarm,
  IconAlarmFilled,
  IconHistory,
  IconCircleCheck,
  IconCircleCheckFilled,
  IconCircleX,
  IconCircleXFilled,
  IconAlertCircle,
  IconAlertCircleFilled,
  IconInfoCircle,
  IconInfoCircleFilled,
  IconQuestionMark,
  IconCircle,
  IconCircleFilled,
  IconSquare,
  IconSquareFilled,
  IconSquareRounded,
  IconSquareRoundedFilled,
  IconTriangle,
  IconTriangleFilled,
  IconHexagon,
  IconHexagonFilled,
  IconPentagon,
  IconPentagonFilled,
  IconDiamond,
  IconDiamondFilled,
  IconCheck,
  IconX,
  IconPlus,
  IconMinus,
  IconHome,
  IconHomeFilled,
  IconUser,
  IconUserFilled,
  IconUsers,
  IconUsersGroup,
  IconEye,
  IconEyeFilled,
  IconSearch,
  IconSettings,
  IconSettingsFilled,
  IconMapPin,
  IconMapPinFilled,
  IconCamera,
  IconCameraFilled,
  IconVideo,
  IconVideoFilled,
  IconMusic,
  IconHeadphones,
  IconHeadphonesFilled,
  IconPlayerPlay,
  IconPlayerPlayFilled,
  IconPlayerPause,
  IconPlayerPauseFilled,
} from '@tabler/icons-react';

export type IconCategory =
  | 'reactions'
  | 'arrows'
  | 'commerce'
  | 'business'
  | 'social'
  | 'time'
  | 'shapes'
  | 'utility';

export interface IconManifestEntry {
  key: string;
  label: string;
  labelPl: string;
  tags: string;
  category: IconCategory;
  component: Icon;
}

export const ICON_CATEGORIES: { key: IconCategory; labelKey: string; fallback: string }[] = [
  { key: 'reactions', labelKey: 'icon_cat_reactions', fallback: 'Reactions' },
  { key: 'arrows', labelKey: 'icon_cat_arrows', fallback: 'Arrows' },
  { key: 'commerce', labelKey: 'icon_cat_commerce', fallback: 'Sales' },
  { key: 'business', labelKey: 'icon_cat_business', fallback: 'Business' },
  { key: 'social', labelKey: 'icon_cat_social', fallback: 'Social' },
  { key: 'time', labelKey: 'icon_cat_time', fallback: 'Time' },
  { key: 'shapes', labelKey: 'icon_cat_shapes', fallback: 'Shapes' },
  { key: 'utility', labelKey: 'icon_cat_utility', fallback: 'Utility' },
];

export const ICONS: IconManifestEntry[] = [
  { key: 'heart', label: 'Heart', labelPl: 'Serce', tags: 'serce love miłość heart', category: 'reactions', component: IconHeart },
  { key: 'heart-filled', label: 'Heart filled', labelPl: 'Serce pełne', tags: 'serce love heart filled', category: 'reactions', component: IconHeartFilled },
  { key: 'thumb-up', label: 'Thumbs up', labelPl: 'Łapka', tags: 'łapka kciuk like thumb', category: 'reactions', component: IconThumbUp },
  { key: 'thumb-up-filled', label: 'Thumbs up filled', labelPl: 'Łapka pełna', tags: 'łapka kciuk like thumb filled', category: 'reactions', component: IconThumbUpFilled },
  { key: 'star', label: 'Star', labelPl: 'Gwiazda', tags: 'gwiazda star ocena rating', category: 'reactions', component: IconStar },
  { key: 'star-filled', label: 'Star filled', labelPl: 'Gwiazda pełna', tags: 'gwiazda star ocena rating', category: 'reactions', component: IconStarFilled },
  { key: 'sparkles', label: 'Sparkles', labelPl: 'Iskry', tags: 'iskry magia ai sparkles magic', category: 'reactions', component: IconSparkles },
  { key: 'flame', label: 'Flame', labelPl: 'Ogień', tags: 'ogień hot fire flame', category: 'reactions', component: IconFlame },
  { key: 'flame-filled', label: 'Flame filled', labelPl: 'Ogień pełny', tags: 'ogień hot fire flame', category: 'reactions', component: IconFlameFilled },
  { key: 'award', label: 'Award', labelPl: 'Medal', tags: 'medal award nagroda prize', category: 'reactions', component: IconAward },
  { key: 'award-filled', label: 'Award filled', labelPl: 'Medal pełny', tags: 'medal award nagroda prize', category: 'reactions', component: IconAwardFilled },
  { key: 'trophy', label: 'Trophy', labelPl: 'Trofeum', tags: 'trofeum trophy zwycięstwo win victory', category: 'reactions', component: IconTrophy },
  { key: 'trophy-filled', label: 'Trophy filled', labelPl: 'Trofeum pełne', tags: 'trofeum trophy zwycięstwo win victory', category: 'reactions', component: IconTrophyFilled },
  { key: 'crown', label: 'Crown', labelPl: 'Korona', tags: 'korona crown king premium', category: 'reactions', component: IconCrown },
  { key: 'bolt', label: 'Bolt', labelPl: 'Piorun', tags: 'piorun szybko bolt energy fast lightning', category: 'reactions', component: IconBolt },
  { key: 'bolt-filled', label: 'Bolt filled', labelPl: 'Piorun pełny', tags: 'piorun szybko bolt energy fast lightning', category: 'reactions', component: IconBoltFilled },
  { key: 'rocket', label: 'Rocket', labelPl: 'Rakieta', tags: 'rakieta start launch rocket', category: 'reactions', component: IconRocket },
  { key: 'verified', label: 'Verified', labelPl: 'Zweryfikowane', tags: 'verified zweryfikowane ptaszek check zaufanie trust', category: 'reactions', component: IconRosetteDiscountCheck },
  { key: 'verified-filled', label: 'Verified filled', labelPl: 'Zweryfikowane pełne', tags: 'verified zweryfikowane check ptaszek', category: 'reactions', component: IconRosetteDiscountCheckFilled },

  { key: 'arrow-right', label: 'Arrow right', labelPl: 'Strzałka w prawo', tags: 'strzałka arrow right next prawo', category: 'arrows', component: IconArrowRight },
  { key: 'arrow-left', label: 'Arrow left', labelPl: 'Strzałka w lewo', tags: 'strzałka arrow left previous lewo', category: 'arrows', component: IconArrowLeft },
  { key: 'arrow-up', label: 'Arrow up', labelPl: 'Strzałka w górę', tags: 'strzałka arrow up góra', category: 'arrows', component: IconArrowUp },
  { key: 'arrow-down', label: 'Arrow down', labelPl: 'Strzałka w dół', tags: 'strzałka arrow down dół', category: 'arrows', component: IconArrowDown },
  { key: 'arrow-up-right', label: 'Arrow up right', labelPl: 'Strzałka NE', tags: 'strzałka arrow right up diagonal', category: 'arrows', component: IconArrowUpRight },
  { key: 'arrow-big-right', label: 'Big arrow', labelPl: 'Duża strzałka', tags: 'strzałka arrow big right duża', category: 'arrows', component: IconArrowBigRight },
  { key: 'arrow-big-right-filled', label: 'Big arrow filled', labelPl: 'Duża strzałka pełna', tags: 'strzałka arrow big right filled duża', category: 'arrows', component: IconArrowBigRightFilled },
  { key: 'arrow-narrow-right', label: 'Narrow arrow', labelPl: 'Cienka strzałka', tags: 'strzałka arrow narrow thin cienka', category: 'arrows', component: IconArrowNarrowRight },
  { key: 'chevron-right', label: 'Chevron right', labelPl: 'Chevron prawy', tags: 'chevron right strzałka prawo', category: 'arrows', component: IconChevronRight },
  { key: 'chevron-left', label: 'Chevron left', labelPl: 'Chevron lewy', tags: 'chevron left strzałka lewo', category: 'arrows', component: IconChevronLeft },
  { key: 'chevron-up', label: 'Chevron up', labelPl: 'Chevron up', tags: 'chevron up strzałka góra', category: 'arrows', component: IconChevronUp },
  { key: 'chevron-down', label: 'Chevron down', labelPl: 'Chevron down', tags: 'chevron down strzałka dół', category: 'arrows', component: IconChevronDown },
  { key: 'circle-arrow-right', label: 'Circle arrow', labelPl: 'Strzałka w kole', tags: 'circle arrow right strzałka koło', category: 'arrows', component: IconCircleArrowRight },
  { key: 'circle-arrow-right-filled', label: 'Circle arrow filled', labelPl: 'Strzałka w kole pełna', tags: 'circle arrow right filled strzałka koło', category: 'arrows', component: IconCircleArrowRightFilled },
  { key: 'arrows-right-left', label: 'Arrows swap', labelPl: 'Strzałki w obie strony', tags: 'arrows swap strzałki zamiana', category: 'arrows', component: IconArrowsRightLeft },
  { key: 'refresh', label: 'Refresh', labelPl: 'Odśwież', tags: 'odśwież refresh reload', category: 'arrows', component: IconRefresh },

  { key: 'shopping-cart', label: 'Cart', labelPl: 'Koszyk', tags: 'koszyk cart shopping zakupy', category: 'commerce', component: IconShoppingCart },
  { key: 'shopping-bag', label: 'Bag', labelPl: 'Torba', tags: 'torba bag shopping zakupy', category: 'commerce', component: IconShoppingBag },
  { key: 'shopping-bag-check', label: 'Shopping check', labelPl: 'Zakupy OK', tags: 'torba zakupy shopping bag check', category: 'commerce', component: IconShoppingBagCheck },
  { key: 'credit-card', label: 'Credit card', labelPl: 'Karta', tags: 'karta credit card płatność payment', category: 'commerce', component: IconCreditCard },
  { key: 'wallet', label: 'Wallet', labelPl: 'Portfel', tags: 'portfel wallet', category: 'commerce', component: IconWallet },
  { key: 'cash', label: 'Cash', labelPl: 'Gotówka', tags: 'gotówka cash money pieniądze', category: 'commerce', component: IconCash },
  { key: 'coin', label: 'Coin', labelPl: 'Moneta', tags: 'moneta coin money pieniądze', category: 'commerce', component: IconCoin },
  { key: 'coin-filled', label: 'Coin filled', labelPl: 'Moneta pełna', tags: 'moneta coin filled money pieniądze', category: 'commerce', component: IconCoinFilled },
  { key: 'currency-dollar', label: 'Dollar', labelPl: 'Dolar', tags: 'dolar dollar usd currency waluta', category: 'commerce', component: IconCurrencyDollar },
  { key: 'currency-euro', label: 'Euro', labelPl: 'Euro', tags: 'euro eur currency waluta', category: 'commerce', component: IconCurrencyEuro },
  { key: 'receipt', label: 'Receipt', labelPl: 'Paragon', tags: 'paragon receipt rachunek bill', category: 'commerce', component: IconReceipt },
  { key: 'receipt-off', label: 'Receipt off', labelPl: 'Paragon off', tags: 'paragon receipt refund zwrot', category: 'commerce', component: IconReceiptOff },
  { key: 'gift', label: 'Gift', labelPl: 'Prezent', tags: 'prezent gift present', category: 'commerce', component: IconGift },
  { key: 'gift-filled', label: 'Gift filled', labelPl: 'Prezent pełny', tags: 'prezent gift present filled', category: 'commerce', component: IconGiftFilled },
  { key: 'discount', label: 'Discount', labelPl: 'Zniżka', tags: 'zniżka discount procent percent sale promocja', category: 'commerce', component: IconDiscount },
  { key: 'discount-filled', label: 'Discount filled', labelPl: 'Zniżka pełna', tags: 'zniżka discount procent percent sale promocja', category: 'commerce', component: IconDiscountFilled },
  { key: 'tag', label: 'Tag', labelPl: 'Etykieta', tags: 'tag etykieta cena price label sale', category: 'commerce', component: IconTag },
  { key: 'tag-filled', label: 'Tag filled', labelPl: 'Etykieta pełna', tags: 'tag etykieta label filled', category: 'commerce', component: IconTagFilled },
  { key: 'tags-filled', label: 'Tags', labelPl: 'Etykiety', tags: 'tags etykiety wiele labels many', category: 'commerce', component: IconTagsFilled },

  { key: 'briefcase', label: 'Briefcase', labelPl: 'Teczka', tags: 'teczka briefcase praca work business', category: 'business', component: IconBriefcase },
  { key: 'briefcase-filled', label: 'Briefcase filled', labelPl: 'Teczka pełna', tags: 'teczka briefcase praca work filled', category: 'business', component: IconBriefcaseFilled },
  { key: 'building-store', label: 'Store', labelPl: 'Sklep', tags: 'sklep store budynek shop building', category: 'business', component: IconBuildingStore },
  { key: 'chart-bar', label: 'Bar chart', labelPl: 'Wykres słupkowy', tags: 'wykres chart bar', category: 'business', component: IconChartBar },
  { key: 'chart-line', label: 'Line chart', labelPl: 'Wykres liniowy', tags: 'wykres chart line', category: 'business', component: IconChartLine },
  { key: 'chart-pie', label: 'Pie chart', labelPl: 'Wykres kołowy', tags: 'wykres chart pie', category: 'business', component: IconChartPie },
  { key: 'chart-pie-filled', label: 'Pie chart filled', labelPl: 'Wykres kołowy pełny', tags: 'wykres chart pie filled', category: 'business', component: IconChartPieFilled },
  { key: 'trending-up', label: 'Trending up', labelPl: 'Wzrost', tags: 'wzrost trend up rosnąco growth chart', category: 'business', component: IconTrendingUp },
  { key: 'trending-down', label: 'Trending down', labelPl: 'Spadek', tags: 'spadek trend down malejąco decline chart', category: 'business', component: IconTrendingDown },
  { key: 'target', label: 'Target', labelPl: 'Cel', tags: 'cel target goal', category: 'business', component: IconTarget },
  { key: 'target-arrow', label: 'Target arrow', labelPl: 'Cel ze strzałą', tags: 'cel target arrow goal strzała', category: 'business', component: IconTargetArrow },

  { key: 'brand-facebook', label: 'Facebook', labelPl: 'Facebook', tags: 'facebook fb meta', category: 'social', component: IconBrandFacebook },
  { key: 'brand-instagram', label: 'Instagram', labelPl: 'Instagram', tags: 'instagram ig', category: 'social', component: IconBrandInstagram },
  { key: 'brand-linkedin', label: 'LinkedIn', labelPl: 'LinkedIn', tags: 'linkedin li', category: 'social', component: IconBrandLinkedin },
  { key: 'brand-tiktok', label: 'TikTok', labelPl: 'TikTok', tags: 'tiktok', category: 'social', component: IconBrandTiktok },
  { key: 'brand-x', label: 'X (Twitter)', labelPl: 'X (Twitter)', tags: 'x twitter', category: 'social', component: IconBrandX },
  { key: 'brand-youtube', label: 'YouTube', labelPl: 'YouTube', tags: 'youtube yt', category: 'social', component: IconBrandYoutube },
  { key: 'brand-whatsapp', label: 'WhatsApp', labelPl: 'WhatsApp', tags: 'whatsapp wa', category: 'social', component: IconBrandWhatsapp },
  { key: 'brand-telegram', label: 'Telegram', labelPl: 'Telegram', tags: 'telegram tg', category: 'social', component: IconBrandTelegram },
  { key: 'brand-pinterest', label: 'Pinterest', labelPl: 'Pinterest', tags: 'pinterest', category: 'social', component: IconBrandPinterest },
  { key: 'brand-snapchat', label: 'Snapchat', labelPl: 'Snapchat', tags: 'snapchat snap', category: 'social', component: IconBrandSnapchat },
  { key: 'share', label: 'Share', labelPl: 'Udostępnij', tags: 'share udostępnij', category: 'social', component: IconShare },
  { key: 'share-2', label: 'Share 2', labelPl: 'Udostępnij 2', tags: 'share udostępnij', category: 'social', component: IconShare2 },
  { key: 'share-3', label: 'Share 3', labelPl: 'Udostępnij 3', tags: 'share udostępnij', category: 'social', component: IconShare3 },
  { key: 'message-circle', label: 'Comment', labelPl: 'Komentarz', tags: 'komentarz comment message circle', category: 'social', component: IconMessageCircle },
  { key: 'message-circle-filled', label: 'Comment filled', labelPl: 'Komentarz pełny', tags: 'komentarz comment message filled', category: 'social', component: IconMessageCircleFilled },
  { key: 'message', label: 'Message', labelPl: 'Wiadomość', tags: 'wiadomość message chat', category: 'social', component: IconMessage },
  { key: 'message-filled', label: 'Message filled', labelPl: 'Wiadomość pełna', tags: 'wiadomość message chat filled', category: 'social', component: IconMessageFilled },
  { key: 'mail', label: 'Mail', labelPl: 'Mail', tags: 'mail email poczta', category: 'social', component: IconMail },
  { key: 'mail-filled', label: 'Mail filled', labelPl: 'Mail pełny', tags: 'mail email poczta filled', category: 'social', component: IconMailFilled },
  { key: 'phone', label: 'Phone', labelPl: 'Telefon', tags: 'telefon phone', category: 'social', component: IconPhone },
  { key: 'phone-filled', label: 'Phone filled', labelPl: 'Telefon pełny', tags: 'telefon phone filled', category: 'social', component: IconPhoneFilled },
  { key: 'bell', label: 'Bell', labelPl: 'Dzwonek', tags: 'dzwonek bell notification powiadomienie', category: 'social', component: IconBell },
  { key: 'bell-filled', label: 'Bell filled', labelPl: 'Dzwonek pełny', tags: 'dzwonek bell notification powiadomienie filled', category: 'social', component: IconBellFilled },
  { key: 'bell-ringing-filled', label: 'Bell ringing', labelPl: 'Dzwonek dzwoni', tags: 'dzwonek bell ringing powiadomienie', category: 'social', component: IconBellRingingFilled },
  { key: 'at', label: 'At sign', labelPl: 'Małpa', tags: 'małpa at email', category: 'social', component: IconAt },
  { key: 'hash', label: 'Hashtag', labelPl: 'Hashtag', tags: 'hashtag hash #', category: 'social', component: IconHash },

  { key: 'calendar', label: 'Calendar', labelPl: 'Kalendarz', tags: 'kalendarz calendar', category: 'time', component: IconCalendar },
  { key: 'calendar-filled', label: 'Calendar filled', labelPl: 'Kalendarz pełny', tags: 'kalendarz calendar filled', category: 'time', component: IconCalendarFilled },
  { key: 'calendar-event', label: 'Event', labelPl: 'Wydarzenie', tags: 'wydarzenie calendar event', category: 'time', component: IconCalendarEvent },
  { key: 'calendar-time', label: 'Calendar time', labelPl: 'Kalendarz czas', tags: 'kalendarz czas calendar time', category: 'time', component: IconCalendarTime },
  { key: 'clock', label: 'Clock', labelPl: 'Zegar', tags: 'zegar clock czas time', category: 'time', component: IconClock },
  { key: 'clock-filled', label: 'Clock filled', labelPl: 'Zegar pełny', tags: 'zegar clock czas time filled', category: 'time', component: IconClockFilled },
  { key: 'clock-hour-9', label: 'Clock 9:00', labelPl: 'Zegar 9:00', tags: 'zegar clock czas time', category: 'time', component: IconClockHour9 },
  { key: 'hourglass', label: 'Hourglass', labelPl: 'Klepsydra', tags: 'klepsydra hourglass', category: 'time', component: IconHourglass },
  { key: 'alarm', label: 'Alarm', labelPl: 'Budzik', tags: 'budzik alarm', category: 'time', component: IconAlarm },
  { key: 'alarm-filled', label: 'Alarm filled', labelPl: 'Budzik pełny', tags: 'budzik alarm filled', category: 'time', component: IconAlarmFilled },
  { key: 'history', label: 'History', labelPl: 'Historia', tags: 'historia history', category: 'time', component: IconHistory },

  { key: 'circle', label: 'Circle', labelPl: 'Koło', tags: 'koło circle', category: 'shapes', component: IconCircle },
  { key: 'circle-filled', label: 'Circle filled', labelPl: 'Koło pełne', tags: 'koło circle filled', category: 'shapes', component: IconCircleFilled },
  { key: 'square', label: 'Square', labelPl: 'Kwadrat', tags: 'kwadrat square', category: 'shapes', component: IconSquare },
  { key: 'square-filled', label: 'Square filled', labelPl: 'Kwadrat pełny', tags: 'kwadrat square filled', category: 'shapes', component: IconSquareFilled },
  { key: 'square-rounded', label: 'Rounded square', labelPl: 'Zaokrąglony', tags: 'rounded square zaokrąglony kwadrat', category: 'shapes', component: IconSquareRounded },
  { key: 'square-rounded-filled', label: 'Rounded square filled', labelPl: 'Zaokrąglony pełny', tags: 'rounded square zaokrąglony kwadrat filled', category: 'shapes', component: IconSquareRoundedFilled },
  { key: 'triangle', label: 'Triangle', labelPl: 'Trójkąt', tags: 'trójkąt triangle', category: 'shapes', component: IconTriangle },
  { key: 'triangle-filled', label: 'Triangle filled', labelPl: 'Trójkąt pełny', tags: 'trójkąt triangle filled', category: 'shapes', component: IconTriangleFilled },
  { key: 'hexagon', label: 'Hexagon', labelPl: 'Sześciokąt', tags: 'sześciokąt hexagon', category: 'shapes', component: IconHexagon },
  { key: 'hexagon-filled', label: 'Hexagon filled', labelPl: 'Sześciokąt pełny', tags: 'sześciokąt hexagon filled', category: 'shapes', component: IconHexagonFilled },
  { key: 'pentagon', label: 'Pentagon', labelPl: 'Pięciokąt', tags: 'pięciokąt pentagon', category: 'shapes', component: IconPentagon },
  { key: 'pentagon-filled', label: 'Pentagon filled', labelPl: 'Pięciokąt pełny', tags: 'pięciokąt pentagon filled', category: 'shapes', component: IconPentagonFilled },
  { key: 'diamond', label: 'Diamond', labelPl: 'Romb', tags: 'romb diamond', category: 'shapes', component: IconDiamond },
  { key: 'diamond-filled', label: 'Diamond filled', labelPl: 'Romb pełny', tags: 'romb diamond filled', category: 'shapes', component: IconDiamondFilled },

  { key: 'check', label: 'Check', labelPl: 'Ptaszek', tags: 'check ptaszek tak ok yes tick', category: 'utility', component: IconCheck },
  { key: 'circle-check', label: 'Circle check', labelPl: 'Ptaszek w kole', tags: 'check circle ptaszek koło', category: 'utility', component: IconCircleCheck },
  { key: 'circle-check-filled', label: 'Circle check filled', labelPl: 'Ptaszek w kole pełny', tags: 'check circle ptaszek koło filled', category: 'utility', component: IconCircleCheckFilled },
  { key: 'x', label: 'X mark', labelPl: 'Krzyżyk', tags: 'x nie no krzyżyk close', category: 'utility', component: IconX },
  { key: 'circle-x', label: 'Circle X', labelPl: 'X w kole', tags: 'x circle close koło', category: 'utility', component: IconCircleX },
  { key: 'circle-x-filled', label: 'Circle X filled', labelPl: 'X w kole pełny', tags: 'x circle close koło filled', category: 'utility', component: IconCircleXFilled },
  { key: 'alert-circle', label: 'Alert', labelPl: 'Uwaga', tags: 'uwaga alert warning', category: 'utility', component: IconAlertCircle },
  { key: 'alert-circle-filled', label: 'Alert filled', labelPl: 'Uwaga pełna', tags: 'uwaga alert warning filled', category: 'utility', component: IconAlertCircleFilled },
  { key: 'info-circle', label: 'Info', labelPl: 'Info', tags: 'info informacja information', category: 'utility', component: IconInfoCircle },
  { key: 'info-circle-filled', label: 'Info filled', labelPl: 'Info pełne', tags: 'info informacja information filled', category: 'utility', component: IconInfoCircleFilled },
  { key: 'question', label: 'Question mark', labelPl: 'Pytajnik', tags: 'pytajnik question help pomoc', category: 'utility', component: IconQuestionMark },
  { key: 'plus', label: 'Plus', labelPl: 'Plus', tags: 'plus dodaj add', category: 'utility', component: IconPlus },
  { key: 'minus', label: 'Minus', labelPl: 'Minus', tags: 'minus odejmij remove', category: 'utility', component: IconMinus },
  { key: 'home', label: 'Home', labelPl: 'Dom', tags: 'dom home', category: 'utility', component: IconHome },
  { key: 'home-filled', label: 'Home filled', labelPl: 'Dom pełny', tags: 'dom home filled', category: 'utility', component: IconHomeFilled },
  { key: 'user', label: 'User', labelPl: 'Użytkownik', tags: 'user użytkownik osoba profil person profile', category: 'utility', component: IconUser },
  { key: 'user-filled', label: 'User filled', labelPl: 'Użytkownik pełny', tags: 'user użytkownik osoba profil person profile filled', category: 'utility', component: IconUserFilled },
  { key: 'users', label: 'Users', labelPl: 'Użytkownicy', tags: 'users grupa zespół group team', category: 'utility', component: IconUsers },
  { key: 'users-group', label: 'Group', labelPl: 'Grupa', tags: 'users grupa zespół group team', category: 'utility', component: IconUsersGroup },
  { key: 'eye', label: 'Eye', labelPl: 'Oko', tags: 'oko eye widok view', category: 'utility', component: IconEye },
  { key: 'eye-filled', label: 'Eye filled', labelPl: 'Oko pełne', tags: 'oko eye widok view filled', category: 'utility', component: IconEyeFilled },
  { key: 'search', label: 'Search', labelPl: 'Szukaj', tags: 'szukaj search lupa magnifier', category: 'utility', component: IconSearch },
  { key: 'settings', label: 'Settings', labelPl: 'Ustawienia', tags: 'ustawienia settings', category: 'utility', component: IconSettings },
  { key: 'settings-filled', label: 'Settings filled', labelPl: 'Ustawienia pełne', tags: 'ustawienia settings filled', category: 'utility', component: IconSettingsFilled },
  { key: 'map-pin', label: 'Map pin', labelPl: 'Pinezka', tags: 'pinezka pin location lokalizacja map', category: 'utility', component: IconMapPin },
  { key: 'map-pin-filled', label: 'Map pin filled', labelPl: 'Pinezka pełna', tags: 'pinezka pin location lokalizacja map filled', category: 'utility', component: IconMapPinFilled },
  { key: 'camera', label: 'Camera', labelPl: 'Aparat', tags: 'aparat camera zdjęcie photo', category: 'utility', component: IconCamera },
  { key: 'camera-filled', label: 'Camera filled', labelPl: 'Aparat pełny', tags: 'aparat camera zdjęcie photo filled', category: 'utility', component: IconCameraFilled },
  { key: 'video', label: 'Video', labelPl: 'Wideo', tags: 'wideo video film', category: 'utility', component: IconVideo },
  { key: 'video-filled', label: 'Video filled', labelPl: 'Wideo pełne', tags: 'wideo video film filled', category: 'utility', component: IconVideoFilled },
  { key: 'music', label: 'Music', labelPl: 'Muzyka', tags: 'muzyka music', category: 'utility', component: IconMusic },
  { key: 'headphones', label: 'Headphones', labelPl: 'Słuchawki', tags: 'słuchawki headphones', category: 'utility', component: IconHeadphones },
  { key: 'headphones-filled', label: 'Headphones filled', labelPl: 'Słuchawki pełne', tags: 'słuchawki headphones filled', category: 'utility', component: IconHeadphonesFilled },
  { key: 'play', label: 'Play', labelPl: 'Odtwórz', tags: 'odtwórz play', category: 'utility', component: IconPlayerPlay },
  { key: 'play-filled', label: 'Play filled', labelPl: 'Odtwórz pełne', tags: 'odtwórz play filled', category: 'utility', component: IconPlayerPlayFilled },
  { key: 'pause', label: 'Pause', labelPl: 'Pauza', tags: 'pauza pause', category: 'utility', component: IconPlayerPause },
  { key: 'pause-filled', label: 'Pause filled', labelPl: 'Pauza pełna', tags: 'pauza pause filled', category: 'utility', component: IconPlayerPauseFilled },
];
