import type { Icon } from '@tabler/icons-react';
import {
  IconHeart,
  IconHeartFilled,
  IconThumbUp,
  IconThumbUpFilled,
  IconStar,
  IconStarFilled,
  IconSparkles,
  IconFlame,
  IconFlameFilled,
  IconAward,
  IconAwardFilled,
  IconTrophy,
  IconTrophyFilled,
  IconCrown,
  IconBolt,
  IconBoltFilled,
  IconRocket,
  IconRosetteDiscountCheck,
  IconRosetteDiscountCheckFilled,
  IconArrowRight,
  IconArrowLeft,
  IconArrowUp,
  IconArrowDown,
  IconArrowUpRight,
  IconArrowBigRight,
  IconArrowBigRightFilled,
  IconArrowNarrowRight,
  IconChevronRight,
  IconChevronLeft,
  IconChevronUp,
  IconChevronDown,
  IconCircleArrowRight,
  IconCircleArrowRightFilled,
  IconArrowsRightLeft,
  IconRefresh,
  IconShoppingCart,
  IconShoppingBag,
  IconShoppingBagCheck,
  IconCreditCard,
  IconWallet,
  IconCash,
  IconCoin,
  IconCoinFilled,
  IconCurrencyDollar,
  IconCurrencyEuro,
  IconReceipt,
  IconReceiptOff,
  IconGift,
  IconGiftFilled,
  IconDiscount,
  IconDiscountFilled,
  IconTag,
  IconTagFilled,
  IconTagsFilled,
  IconBriefcase,
  IconBriefcaseFilled,
  IconBuildingStore,
  IconChartBar,
  IconChartLine,
  IconChartPie,
  IconChartPieFilled,
  IconTrendingUp,
  IconTrendingDown,
  IconTarget,
  IconTargetArrow,
  IconBrandFacebook,
  IconBrandInstagram,
  IconBrandLinkedin,
  IconBrandTiktok,
  IconBrandX,
  IconBrandYoutube,
  IconBrandWhatsapp,
  IconBrandTelegram,
  IconBrandPinterest,
  IconBrandSnapchat,
  IconShare,
  IconShare2,
  IconShare3,
  IconMessageCircle,
  IconMessageCircleFilled,
  IconMessage,
  IconMessageFilled,
  IconMail,
  IconMailFilled,
  IconPhone,
  IconPhoneFilled,
  IconBell,
  IconBellFilled,
  IconBellRingingFilled,
  IconAt,
  IconHash,
  IconCalendar,
  IconCalendarFilled,
  IconCalendarEvent,
  IconCalendarTime,
  IconClock,
  IconClockFilled,
  IconClockHour9,
  IconHourglass,
  IconAlarm,
  IconAlarmFilled,
  IconHistory,
  IconCircleCheck,
  IconCircleCheckFilled,
  IconCircleX,
  IconCircleXFilled,
  IconAlertCircle,
  IconAlertCircleFilled,
  IconInfoCircle,
  IconInfoCircleFilled,
  IconQuestionMark,
  IconCircle,
  IconCircleFilled,
  IconSquare,
  IconSquareFilled,
  IconSquareRounded,
  IconSquareRoundedFilled,
  IconTriangle,
  IconTriangleFilled,
  IconHexagon,
  IconHexagonFilled,
  IconPentagon,
  IconPentagonFilled,
  IconDiamond,
  IconDiamondFilled,
  IconCheck,
  IconX,
  IconPlus,
  IconMinus,
  IconHome,
  IconHomeFilled,
  IconUser,
  IconUserFilled,
  IconUsers,
  IconUsersGroup,
  IconEye,
  IconEyeFilled,
  IconSearch,
  IconSettings,
  IconSettingsFilled,
  IconMapPin,
  IconMapPinFilled,
  IconCamera,
  IconCameraFilled,
  IconVideo,
  IconVideoFilled,
  IconMusic,
  IconHeadphones,
  IconHeadphonesFilled,
  IconPlayerPlay,
  IconPlayerPlayFilled,
  IconPlayerPause,
  IconPlayerPauseFilled,
} from '@tabler/icons-react';

export type IconCategory =
  | 'reactions'
  | 'arrows'
  | 'commerce'
  | 'business'
  | 'social'
  | 'time'
  | 'shapes'
  | 'utility';

export interface IconManifestEntry {
  key: string;
  label: string;
  tags: string;
  category: IconCategory;
  component: Icon;
}

export const ICON_CATEGORIES: { key: IconCategory; labelKey: string; fallback: string }[] = [
  { key: 'reactions', labelKey: 'icon_cat_reactions', fallback: 'Reakcje' },
  { key: 'arrows', labelKey: 'icon_cat_arrows', fallback: 'Strzałki' },
  { key: 'commerce', labelKey: 'icon_cat_commerce', fallback: 'Sprzedaż' },
  { key: 'business', labelKey: 'icon_cat_business', fallback: 'Biznes' },
  { key: 'social', labelKey: 'icon_cat_social', fallback: 'Social' },
  { key: 'time', labelKey: 'icon_cat_time', fallback: 'Czas' },
  { key: 'shapes', labelKey: 'icon_cat_shapes', fallback: 'Kształty' },
  { key: 'utility', labelKey: 'icon_cat_utility', fallback: 'Użytkowe' },
];

export const ICONS: IconManifestEntry[] = [
  { key: 'heart', label: 'Serce', tags: 'serce love miłość heart', category: 'reactions', component: IconHeart },
  { key: 'heart-filled', label: 'Serce pełne', tags: 'serce love heart filled', category: 'reactions', component: IconHeartFilled },
  { key: 'thumb-up', label: 'Łapka', tags: 'łapka kciuk like thumb', category: 'reactions', component: IconThumbUp },
  { key: 'thumb-up-filled', label: 'Łapka pełna', tags: 'łapka kciuk like thumb filled', category: 'reactions', component: IconThumbUpFilled },
  { key: 'star', label: 'Gwiazda', tags: 'gwiazda star ocena', category: 'reactions', component: IconStar },
  { key: 'star-filled', label: 'Gwiazda pełna', tags: 'gwiazda star ocena', category: 'reactions', component: IconStarFilled },
  { key: 'sparkles', label: 'Iskry', tags: 'iskry magia ai sparkles', category: 'reactions', component: IconSparkles },
  { key: 'flame', label: 'Ogień', tags: 'ogień hot fire flame', category: 'reactions', component: IconFlame },
  { key: 'flame-filled', label: 'Ogień pełny', tags: 'ogień hot fire flame', category: 'reactions', component: IconFlameFilled },
  { key: 'award', label: 'Medal', tags: 'medal award nagroda', category: 'reactions', component: IconAward },
  { key: 'award-filled', label: 'Medal pełny', tags: 'medal award nagroda', category: 'reactions', component: IconAwardFilled },
  { key: 'trophy', label: 'Trofeum', tags: 'trofeum trophy zwycięstwo', category: 'reactions', component: IconTrophy },
  { key: 'trophy-filled', label: 'Trofeum pełne', tags: 'trofeum trophy zwycięstwo', category: 'reactions', component: IconTrophyFilled },
  { key: 'crown', label: 'Korona', tags: 'korona king premium', category: 'reactions', component: IconCrown },
  { key: 'bolt', label: 'Piorun', tags: 'piorun szybko bolt energy', category: 'reactions', component: IconBolt },
  { key: 'bolt-filled', label: 'Piorun pełny', tags: 'piorun szybko bolt energy', category: 'reactions', component: IconBoltFilled },
  { key: 'rocket', label: 'Rakieta', tags: 'rakieta start launch rocket', category: 'reactions', component: IconRocket },
  { key: 'verified', label: 'Zweryfikowane', tags: 'verified ptaszek check zaufanie', category: 'reactions', component: IconRosetteDiscountCheck },
  { key: 'verified-filled', label: 'Zweryfikowane pełne', tags: 'verified check', category: 'reactions', component: IconRosetteDiscountCheckFilled },

  { key: 'arrow-right', label: 'Strzałka w prawo', tags: 'strzałka right next', category: 'arrows', component: IconArrowRight },
  { key: 'arrow-left', label: 'Strzałka w lewo', tags: 'strzałka left previous', category: 'arrows', component: IconArrowLeft },
  { key: 'arrow-up', label: 'Strzałka w górę', tags: 'strzałka up góra', category: 'arrows', component: IconArrowUp },
  { key: 'arrow-down', label: 'Strzałka w dół', tags: 'strzałka down dół', category: 'arrows', component: IconArrowDown },
  { key: 'arrow-up-right', label: 'Strzałka NE', tags: 'strzałka right up', category: 'arrows', component: IconArrowUpRight },
  { key: 'arrow-big-right', label: 'Duża strzałka', tags: 'strzałka big right', category: 'arrows', component: IconArrowBigRight },
  { key: 'arrow-big-right-filled', label: 'Duża strzałka pełna', tags: 'strzałka big right filled', category: 'arrows', component: IconArrowBigRightFilled },
  { key: 'arrow-narrow-right', label: 'Cienka strzałka', tags: 'strzałka narrow thin', category: 'arrows', component: IconArrowNarrowRight },
  { key: 'chevron-right', label: 'Chevron prawy', tags: 'chevron right', category: 'arrows', component: IconChevronRight },
  { key: 'chevron-left', label: 'Chevron lewy', tags: 'chevron left', category: 'arrows', component: IconChevronLeft },
  { key: 'chevron-up', label: 'Chevron up', tags: 'chevron up', category: 'arrows', component: IconChevronUp },
  { key: 'chevron-down', label: 'Chevron down', tags: 'chevron down', category: 'arrows', component: IconChevronDown },
  { key: 'circle-arrow-right', label: 'Strzałka w kole', tags: 'circle arrow right', category: 'arrows', component: IconCircleArrowRight },
  { key: 'circle-arrow-right-filled', label: 'Strzałka w kole pełna', tags: 'circle arrow right filled', category: 'arrows', component: IconCircleArrowRightFilled },
  { key: 'arrows-right-left', label: 'Strzałki w obie strony', tags: 'arrows swap', category: 'arrows', component: IconArrowsRightLeft },
  { key: 'refresh', label: 'Odśwież', tags: 'odśwież refresh reload', category: 'arrows', component: IconRefresh },

  { key: 'shopping-cart', label: 'Koszyk', tags: 'koszyk cart shopping', category: 'commerce', component: IconShoppingCart },
  { key: 'shopping-bag', label: 'Torba', tags: 'torba bag shopping', category: 'commerce', component: IconShoppingBag },
  { key: 'shopping-bag-check', label: 'Zakupy OK', tags: 'torba shopping check', category: 'commerce', component: IconShoppingBagCheck },
  { key: 'credit-card', label: 'Karta', tags: 'karta credit card płatność', category: 'commerce', component: IconCreditCard },
  { key: 'wallet', label: 'Portfel', tags: 'portfel wallet', category: 'commerce', component: IconWallet },
  { key: 'cash', label: 'Gotówka', tags: 'gotówka cash money pieniądze', category: 'commerce', component: IconCash },
  { key: 'coin', label: 'Moneta', tags: 'moneta coin', category: 'commerce', component: IconCoin },
  { key: 'coin-filled', label: 'Moneta pełna', tags: 'moneta coin filled', category: 'commerce', component: IconCoinFilled },
  { key: 'currency-dollar', label: 'Dolar', tags: 'dolar dollar usd', category: 'commerce', component: IconCurrencyDollar },
  { key: 'currency-euro', label: 'Euro', tags: 'euro eur', category: 'commerce', component: IconCurrencyEuro },
  { key: 'receipt', label: 'Paragon', tags: 'paragon receipt rachunek', category: 'commerce', component: IconReceipt },
  { key: 'receipt-off', label: 'Paragon off', tags: 'paragon refund', category: 'commerce', component: IconReceiptOff },
  { key: 'gift', label: 'Prezent', tags: 'prezent gift', category: 'commerce', component: IconGift },
  { key: 'gift-filled', label: 'Prezent pełny', tags: 'prezent gift filled', category: 'commerce', component: IconGiftFilled },
  { key: 'discount', label: 'Zniżka', tags: 'zniżka discount procent', category: 'commerce', component: IconDiscount },
  { key: 'discount-filled', label: 'Zniżka pełna', tags: 'zniżka discount procent', category: 'commerce', component: IconDiscountFilled },
  { key: 'tag', label: 'Etykieta', tags: 'tag etykieta cena', category: 'commerce', component: IconTag },
  { key: 'tag-filled', label: 'Etykieta pełna', tags: 'tag etykieta', category: 'commerce', component: IconTagFilled },
  { key: 'tags-filled', label: 'Etykiety', tags: 'tags etykiety wiele', category: 'commerce', component: IconTagsFilled },

  { key: 'briefcase', label: 'Teczka', tags: 'teczka briefcase praca', category: 'business', component: IconBriefcase },
  { key: 'briefcase-filled', label: 'Teczka pełna', tags: 'teczka briefcase', category: 'business', component: IconBriefcaseFilled },
  { key: 'building-store', label: 'Sklep', tags: 'sklep store budynek', category: 'business', component: IconBuildingStore },
  { key: 'chart-bar', label: 'Wykres słupkowy', tags: 'wykres chart bar', category: 'business', component: IconChartBar },
  { key: 'chart-line', label: 'Wykres liniowy', tags: 'wykres chart line', category: 'business', component: IconChartLine },
  { key: 'chart-pie', label: 'Wykres kołowy', tags: 'wykres chart pie', category: 'business', component: IconChartPie },
  { key: 'chart-pie-filled', label: 'Wykres kołowy pełny', tags: 'wykres chart pie filled', category: 'business', component: IconChartPieFilled },
  { key: 'trending-up', label: 'Wzrost', tags: 'wzrost trend up rosnąco', category: 'business', component: IconTrendingUp },
  { key: 'trending-down', label: 'Spadek', tags: 'spadek trend down malejąco', category: 'business', component: IconTrendingDown },
  { key: 'target', label: 'Cel', tags: 'cel target', category: 'business', component: IconTarget },
  { key: 'target-arrow', label: 'Cel ze strzałą', tags: 'cel target arrow', category: 'business', component: IconTargetArrow },

  { key: 'brand-facebook', label: 'Facebook', tags: 'facebook fb meta', category: 'social', component: IconBrandFacebook },
  { key: 'brand-instagram', label: 'Instagram', tags: 'instagram ig', category: 'social', component: IconBrandInstagram },
  { key: 'brand-linkedin', label: 'LinkedIn', tags: 'linkedin li', category: 'social', component: IconBrandLinkedin },
  { key: 'brand-tiktok', label: 'TikTok', tags: 'tiktok', category: 'social', component: IconBrandTiktok },
  { key: 'brand-x', label: 'X (Twitter)', tags: 'x twitter', category: 'social', component: IconBrandX },
  { key: 'brand-youtube', label: 'YouTube', tags: 'youtube yt', category: 'social', component: IconBrandYoutube },
  { key: 'brand-whatsapp', label: 'WhatsApp', tags: 'whatsapp wa', category: 'social', component: IconBrandWhatsapp },
  { key: 'brand-telegram', label: 'Telegram', tags: 'telegram tg', category: 'social', component: IconBrandTelegram },
  { key: 'brand-pinterest', label: 'Pinterest', tags: 'pinterest', category: 'social', component: IconBrandPinterest },
  { key: 'brand-snapchat', label: 'Snapchat', tags: 'snapchat snap', category: 'social', component: IconBrandSnapchat },
  { key: 'share', label: 'Udostępnij', tags: 'share udostępnij', category: 'social', component: IconShare },
  { key: 'share-2', label: 'Udostępnij 2', tags: 'share udostępnij', category: 'social', component: IconShare2 },
  { key: 'share-3', label: 'Udostępnij 3', tags: 'share udostępnij', category: 'social', component: IconShare3 },
  { key: 'message-circle', label: 'Komentarz', tags: 'komentarz message circle', category: 'social', component: IconMessageCircle },
  { key: 'message-circle-filled', label: 'Komentarz pełny', tags: 'komentarz message', category: 'social', component: IconMessageCircleFilled },
  { key: 'message', label: 'Wiadomość', tags: 'wiadomość message', category: 'social', component: IconMessage },
  { key: 'message-filled', label: 'Wiadomość pełna', tags: 'wiadomość message', category: 'social', component: IconMessageFilled },
  { key: 'mail', label: 'Mail', tags: 'mail email', category: 'social', component: IconMail },
  { key: 'mail-filled', label: 'Mail pełny', tags: 'mail email', category: 'social', component: IconMailFilled },
  { key: 'phone', label: 'Telefon', tags: 'telefon phone', category: 'social', component: IconPhone },
  { key: 'phone-filled', label: 'Telefon pełny', tags: 'telefon phone', category: 'social', component: IconPhoneFilled },
  { key: 'bell', label: 'Dzwonek', tags: 'dzwonek bell notification', category: 'social', component: IconBell },
  { key: 'bell-filled', label: 'Dzwonek pełny', tags: 'dzwonek bell', category: 'social', component: IconBellFilled },
  { key: 'bell-ringing-filled', label: 'Dzwonek dzwoni', tags: 'dzwonek bell ringing', category: 'social', component: IconBellRingingFilled },
  { key: 'at', label: 'Małpa', tags: 'małpa at email', category: 'social', component: IconAt },
  { key: 'hash', label: 'Hashtag', tags: 'hashtag hash #', category: 'social', component: IconHash },

  { key: 'calendar', label: 'Kalendarz', tags: 'kalendarz calendar', category: 'time', component: IconCalendar },
  { key: 'calendar-filled', label: 'Kalendarz pełny', tags: 'kalendarz calendar', category: 'time', component: IconCalendarFilled },
  { key: 'calendar-event', label: 'Wydarzenie', tags: 'wydarzenie calendar event', category: 'time', component: IconCalendarEvent },
  { key: 'calendar-time', label: 'Kalendarz czas', tags: 'kalendarz czas calendar time', category: 'time', component: IconCalendarTime },
  { key: 'clock', label: 'Zegar', tags: 'zegar clock', category: 'time', component: IconClock },
  { key: 'clock-filled', label: 'Zegar pełny', tags: 'zegar clock', category: 'time', component: IconClockFilled },
  { key: 'clock-hour-9', label: 'Zegar 9:00', tags: 'zegar clock', category: 'time', component: IconClockHour9 },
  { key: 'hourglass', label: 'Klepsydra', tags: 'klepsydra hourglass', category: 'time', component: IconHourglass },
  { key: 'alarm', label: 'Budzik', tags: 'budzik alarm', category: 'time', component: IconAlarm },
  { key: 'alarm-filled', label: 'Budzik pełny', tags: 'budzik alarm', category: 'time', component: IconAlarmFilled },
  { key: 'history', label: 'Historia', tags: 'historia history', category: 'time', component: IconHistory },

  { key: 'circle', label: 'Koło', tags: 'koło circle', category: 'shapes', component: IconCircle },
  { key: 'circle-filled', label: 'Koło pełne', tags: 'koło circle', category: 'shapes', component: IconCircleFilled },
  { key: 'square', label: 'Kwadrat', tags: 'kwadrat square', category: 'shapes', component: IconSquare },
  { key: 'square-filled', label: 'Kwadrat pełny', tags: 'kwadrat square', category: 'shapes', component: IconSquareFilled },
  { key: 'square-rounded', label: 'Zaokrąglony', tags: 'rounded square', category: 'shapes', component: IconSquareRounded },
  { key: 'square-rounded-filled', label: 'Zaokrąglony pełny', tags: 'rounded square', category: 'shapes', component: IconSquareRoundedFilled },
  { key: 'triangle', label: 'Trójkąt', tags: 'trójkąt triangle', category: 'shapes', component: IconTriangle },
  { key: 'triangle-filled', label: 'Trójkąt pełny', tags: 'trójkąt triangle', category: 'shapes', component: IconTriangleFilled },
  { key: 'hexagon', label: 'Sześciokąt', tags: 'sześciokąt hexagon', category: 'shapes', component: IconHexagon },
  { key: 'hexagon-filled', label: 'Sześciokąt pełny', tags: 'sześciokąt hexagon', category: 'shapes', component: IconHexagonFilled },
  { key: 'pentagon', label: 'Pięciokąt', tags: 'pięciokąt pentagon', category: 'shapes', component: IconPentagon },
  { key: 'pentagon-filled', label: 'Pięciokąt pełny', tags: 'pięciokąt pentagon', category: 'shapes', component: IconPentagonFilled },
  { key: 'diamond', label: 'Romb', tags: 'romb diamond', category: 'shapes', component: IconDiamond },
  { key: 'diamond-filled', label: 'Romb pełny', tags: 'romb diamond', category: 'shapes', component: IconDiamondFilled },

  { key: 'check', label: 'Ptaszek', tags: 'check ptaszek tak ok', category: 'utility', component: IconCheck },
  { key: 'circle-check', label: 'Ptaszek w kole', tags: 'check circle ptaszek', category: 'utility', component: IconCircleCheck },
  { key: 'circle-check-filled', label: 'Ptaszek w kole pełny', tags: 'check circle', category: 'utility', component: IconCircleCheckFilled },
  { key: 'x', label: 'Krzyżyk', tags: 'x nie krzyżyk close', category: 'utility', component: IconX },
  { key: 'circle-x', label: 'X w kole', tags: 'x circle close', category: 'utility', component: IconCircleX },
  { key: 'circle-x-filled', label: 'X w kole pełny', tags: 'x circle close', category: 'utility', component: IconCircleXFilled },
  { key: 'alert-circle', label: 'Uwaga', tags: 'uwaga alert warning', category: 'utility', component: IconAlertCircle },
  { key: 'alert-circle-filled', label: 'Uwaga pełna', tags: 'uwaga alert warning', category: 'utility', component: IconAlertCircleFilled },
  { key: 'info-circle', label: 'Info', tags: 'info informacja', category: 'utility', component: IconInfoCircle },
  { key: 'info-circle-filled', label: 'Info pełne', tags: 'info informacja', category: 'utility', component: IconInfoCircleFilled },
  { key: 'question', label: 'Pytajnik', tags: 'pytajnik question help', category: 'utility', component: IconQuestionMark },
  { key: 'plus', label: 'Plus', tags: 'plus dodaj add', category: 'utility', component: IconPlus },
  { key: 'minus', label: 'Minus', tags: 'minus odejmij remove', category: 'utility', component: IconMinus },
  { key: 'home', label: 'Dom', tags: 'dom home', category: 'utility', component: IconHome },
  { key: 'home-filled', label: 'Dom pełny', tags: 'dom home', category: 'utility', component: IconHomeFilled },
  { key: 'user', label: 'Użytkownik', tags: 'user osoba profil', category: 'utility', component: IconUser },
  { key: 'user-filled', label: 'Użytkownik pełny', tags: 'user osoba profil', category: 'utility', component: IconUserFilled },
  { key: 'users', label: 'Użytkownicy', tags: 'users grupa zespół', category: 'utility', component: IconUsers },
  { key: 'users-group', label: 'Grupa', tags: 'users grupa zespół', category: 'utility', component: IconUsersGroup },
  { key: 'eye', label: 'Oko', tags: 'oko eye widok', category: 'utility', component: IconEye },
  { key: 'eye-filled', label: 'Oko pełne', tags: 'oko eye', category: 'utility', component: IconEyeFilled },
  { key: 'search', label: 'Szukaj', tags: 'szukaj search lupa', category: 'utility', component: IconSearch },
  { key: 'settings', label: 'Ustawienia', tags: 'ustawienia settings', category: 'utility', component: IconSettings },
  { key: 'settings-filled', label: 'Ustawienia pełne', tags: 'ustawienia settings', category: 'utility', component: IconSettingsFilled },
  { key: 'map-pin', label: 'Pinezka', tags: 'pinezka location lokalizacja', category: 'utility', component: IconMapPin },
  { key: 'map-pin-filled', label: 'Pinezka pełna', tags: 'pinezka location', category: 'utility', component: IconMapPinFilled },
  { key: 'camera', label: 'Aparat', tags: 'aparat camera', category: 'utility', component: IconCamera },
  { key: 'camera-filled', label: 'Aparat pełny', tags: 'aparat camera', category: 'utility', component: IconCameraFilled },
  { key: 'video', label: 'Wideo', tags: 'wideo video', category: 'utility', component: IconVideo },
  { key: 'video-filled', label: 'Wideo pełne', tags: 'wideo video', category: 'utility', component: IconVideoFilled },
  { key: 'music', label: 'Muzyka', tags: 'muzyka music', category: 'utility', component: IconMusic },
  { key: 'headphones', label: 'Słuchawki', tags: 'słuchawki headphones', category: 'utility', component: IconHeadphones },
  { key: 'headphones-filled', label: 'Słuchawki pełne', tags: 'słuchawki headphones', category: 'utility', component: IconHeadphonesFilled },
  { key: 'play', label: 'Odtwórz', tags: 'odtwórz play', category: 'utility', component: IconPlayerPlay },
  { key: 'play-filled', label: 'Odtwórz pełne', tags: 'odtwórz play', category: 'utility', component: IconPlayerPlayFilled },
  { key: 'pause', label: 'Pauza', tags: 'pauza pause', category: 'utility', component: IconPlayerPause },
  { key: 'pause-filled', label: 'Pauza pełna', tags: 'pauza pause', category: 'utility', component: IconPlayerPauseFilled },
];
